# TODO: move this task to container.yml and create only what's necessary!
- name: easydb directories under {{ easydb_basedir }}
  file:
    state: directory
    path: "{{ file_item.path }}"
    owner: "{{ file_item.owner | default('root') }}"
    group: "{{ file_item.group | default('root') }}"
    mode: "{{ file_item.mode | default('0755') }}"
  loop_control:
    loop_var: file_item
  with_items:
    - path: "{{ easydb_basedir }}"
    - path: "{{ easydb_volume_config }}"
    - path: "{{ easydb_eas_volume_assets }}"
      owner: www-data
      group: www-data
    - path: "{{ easydb_eas_volume_log }}"
    - path: "{{ easydb_eas_volume_tmp }}"
      mode: u=rwx,g=rwx,o=rwx,o+t
    - path: "{{ easydb_elasticsearch_volume_var }}"
      mode: u=rwx,g=rwx,o=rwx
    - path: "{{ easydb_pgsql_volume_backup }}"
    - path: "{{ easydb_pgsql_volume_etc }}"
    - path: "{{ easydb_pgsql_volume_lib }}"
    - path: "{{ easydb_pgsql_volume_log }}"
    - path: "{{ easydb_server_volume_nginx_log }}"
      mode: u=rwx,g=rwx,o=rwx
    - path: "{{ easydb_server_volume_var }}"
    - path: "{{ easydb_server_volume_hotfolder }}"
    - path: "{{ easydb_flyr_volume_objectstore }}"
      owner: 1000
      group: 1000

- name: installing maintain script
  template:
    src: srv/easydb/maintain
    dest: "{{ easydb_basedir }}/maintain"
    owner: root
    group: root
    mode: 0755

- name: central configuration file
  when: easydb_has_old_master_config
  template:
    src: srv/easydb/config/easydb5-master.yml.j2
    dest: "{{ easydb_basedir }}/config/easydb5-master.yml"
    owner: root
    group: root
    mode: 0644
  register: has_config_changed

- name: removing old central configuration files
  when: not easydb_has_old_master_config
  file:
    path: "{{ easydb_basedir }}/config/easydb5-master.yml"
    state: absent
  register: has_config_changed

- name: old EAS configuration file
  when: easydb_has_old_master_config
  template:
    src: srv/easydb/config/easydb_asset_server.conf.j2
    dest: "{{ easydb_basedir }}/config/easydb_asset_server.conf"
    owner: root
    group: root
    mode: 0644
  register: has_config_changed

- name: removing old EAS configuration file
  when: not easydb_has_old_master_config
  file:
    path: "{{ easydb_basedir }}/config/easydb_asset_server.conf"
    state: absent
  register: has_config_changed

- name: logging in to docker registry
  docker_login:
    registry: "{{ easydb_docker_registry }}"
    username: "{{ easydb_docker_user }}"
    password: "{{ easydb_docker_pass }}"
    reauthorize: yes

# Flush handlers now so the docker daemon doesn't restart immediatly after the instances have started.
- meta: flush_handlers

- name: creating easydb5 docker network
  docker_network:
    name: "{{ easydb_container_network }}"

- name: spinning up docker-containers
  with_items: "{{ easydb_containers_deploy_these }}"
  loop_control:
    loop_var: easydb_container
  include_tasks: containers/{{ easydb_container }}.yml
