---
vagrant:
  raw_config_args:
    - "vm.network 'forwarded_port', guest: 80, host: 8080"
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: stretch
    box: bento/debian-9.0
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: install
verifier:
  name: testinfra
  lint:
    name: flake8
