- name: "Developing options: "
  debug:
    msg: "Playbook directory {{ playbook_dir }}"

- name: deploying run-scripts
  template:
    src: srv/easydb/run-script.j2
    dest: "{{ easydb_basedir }}/run-{{ easydb_container }}.sh"
    owner: root
    group: root
    mode: 0750

- name: deploying configuration
  template:
    src: srv/easydb/config/{{ easydb_containers[easydb_container]['configs']['src'] }}.yml.j2
    dest: "{{ easydb_basedir}}/config/{{ easydb_containers[easydb_container]['configs']['dest'] }}.yml"
    owner: root
    group: root
    mode: 0644
  register: has_new_config_changed

- name: "Copying eas_produce.json"
  copy:
    src: "{{playbook_dir}}/eas.d/eas_produce.json"
    dest: "{{ easydb_basedir}}/config/eas_produce.json"
    owner: root
    group: root
    mode: 0644
  when: easydb_eas_custom_version_enabled == True or easydb_eas_watermark_enabled == True
  
- name: "Copying eas_rights_management.json"
  copy:
    src: "{{playbook_dir}}/eas.d/eas_rights_management.yml"
    dest: "{{ easydb_basedir}}/config/eas_rights_management.yml"
    owner: root
    group: root
    mode: 0644
  when: easydb_eas_custom_version_enabled == True or easydb_eas_watermark_enabled == True

- name: stopping container (if running)
  when: has_config_changed.changed or has_new_config_changed.changed
  shell: docker stop easydb-{{ easydb_container }}
  failed_when: no

- name: spinning up container
  docker_container:
    name: "{{ easydb_containers[easydb_container].container_name }}"
    image: "{{ easydb_containers[easydb_container].image }}"
    networks:
      - name: "{{ easydb_containers[easydb_container].network | default(easydb_container_network) }}"
    restart_policy: "{{ easydb_containers[easydb_container].restart_policy | default('always') }}"
    ports: "{{ easydb_containers[easydb_container].ports | default([]) }}"
    volumes: "{{ easydb_containers[easydb_container].volumes | default([]) }}"
    capabilities: "{{ easydb_containers[easydb_container].capabilities | default([]) }}"
    security_opts:
      - "seccomp=unconfined"
    etc_hosts: "{{ easydb_etc_hosts[inventory_hostname] | default({}) }}"
