---
- name: Converge
  become: yes
  hosts: all
  vars:
    docker_enabled: yes
    docker_compose_version: 1.22.0

    easydb_url: http://localhost:8080
    easydb_customer_id: be52ae33594eb794828ccd4837cf08ae
    easydb_solution: base
    easydb_docker_user: user1
    easydb_docker_pass: HA-imUsE3Dj

  roles:
    - role: role-easydb
