- hosts: all
  become: yes
  vars:
    docker_enabled: yes
    docker_compose_enabled: yes
    docker_compose_version: 1.22.0

    easydb_url: http://localhost:8080
    easydb_solution: base
    easydb_docker_user: user1
    easydb_docker_pass: HA-imUsE3Dj
  
  roles:
    - role-easydb
  
